/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Produccionn;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import modelo.Conexion;

/**
 *
 * @author EQUIPO
 */
public class DetalleEtapa extends javax.swing.JPanel {

    private int idEtapa;

    /**
     * Creates new form DetalleEtapa
     */
    public DetalleEtapa(int id, String nombre, String cantidad, String fechaInicio, String fechaFin, String estado, String materiales, String herramientas, String asignado) {
        this.idEtapa = id;
        initComponents();

        this.nombre.setText(nombre != null ? nombre : "No especificado");
        this.fecha_ini.setText(fechaInicio != null ? fechaInicio : "No definida");
        this.fecha_fin.setText(fechaFin != null ? fechaFin : "No definida");
        this.estado.setText(estado != null ? estado : "Sin estado");
        this.cantidad.setText(cantidad != null ? cantidad : "0");
        this.materiales.setText(materiales != null ? materiales : "No especificado");
        this.herramientas.setText(herramientas != null ? herramientas : "No especificado");
        this.asignado.setText(asignado != null ? asignado : "No asignado");

        cargarDatosEtapa();
    }

private void cargarDatosEtapa() {
    try (Connection con = new Conexion().getConnection()) {
        String sql = "SELECT ep.nombre_etapa, ep.estado, ep.fecha_inicio, ep.fecha_fin, " +
                    "ep.cantidad, CONCAT(u.nombre, ' ', u.apellido) AS asignado, " +
                    "GROUP_CONCAT(DISTINCT CASE WHEN i.tipo = 'material' THEN i.nombre END SEPARATOR ', ') AS materiales, " +
                    "GROUP_CONCAT(DISTINCT CASE WHEN i.tipo = 'herramienta' THEN i.nombre END SEPARATOR ', ') AS herramientas " +
                    "FROM etapa_produccion ep " +
                    "LEFT JOIN usuario u ON ep.asignado_a = u.idusuarios " +
                    "LEFT JOIN utilizado ut ON ep.idetapa_produccion = ut.etapa_produccion_idetapa_produccion " +
                    "LEFT JOIN inventario i ON ie.utilizado = i.id_inventario " +
                    "WHERE ep.idetapa_produccion = ? " +
                    "GROUP BY ep.idetapa_produccion";
        
        try (PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, this.idEtapa);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    
                    nombre.setText(rs.getString("nombre_etapa"));
                    cantidad.setText(String.valueOf(rs.getInt("cantidad")));
                    
                    Date fechaInicio = rs.getDate("fecha_inicio");
                    Date fechaFin = rs.getDate("fecha_fin");
                    fecha_ini.setText(fechaInicio != null ? sdf.format(fechaInicio) : "No definida");
                    fecha_fin.setText(fechaFin != null ? sdf.format(fechaFin) : "No definida");
                    
                    estado.setText(rs.getString("estado"));
                    asignado.setText(rs.getString("asignado") != null ? 
                                   rs.getString("asignado") : "No asignado");
                    
                    materiales.setText(rs.getString("materiales") != null ? 
                                    rs.getString("materiales") : "Sin materiales");
                    herramientas.setText(rs.getString("herramientas") != null ? 
                                       rs.getString("herramientas") : "Sin herramientas");
                }
            }
        }
    } catch (SQLException e) {
        // Manejo de errores igual que antes
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fecha_ini = new javax.swing.JLabel();
        fecha_fin = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        materiales = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        herramientas = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        asignado = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 234, 234));

        jPanel2.setBackground(new java.awt.Color(234, 234, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        fecha_ini.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_ini.setForeground(new java.awt.Color(0, 0, 0));
        fecha_ini.setText("fecha_ini");
        jPanel2.add(fecha_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        fecha_fin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_fin.setForeground(new java.awt.Color(0, 0, 0));
        fecha_fin.setText("fecha_fin");
        jPanel2.add(fecha_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 0, 0));
        cantidad.setText("cantidad");
        jPanel2.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        materiales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        materiales.setForeground(new java.awt.Color(0, 0, 0));
        materiales.setText("materiales");
        jPanel2.add(materiales, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        estado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estado.setForeground(new java.awt.Color(0, 0, 0));
        estado.setText("estado");
        jPanel2.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 700, 2));

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setText("Nombre");
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fecha de fin:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Material:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Estado:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fecha de inicio: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        herramientas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        herramientas.setForeground(new java.awt.Color(0, 0, 0));
        herramientas.setText("herramientas");
        jPanel2.add(herramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Herramientas:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        asignado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        asignado.setForeground(new java.awt.Color(0, 0, 0));
        asignado.setText("asignado");
        jPanel2.add(asignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Asignado:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asignado;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fecha_fin;
    private javax.swing.JLabel fecha_ini;
    private javax.swing.JLabel herramientas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel materiales;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
