/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Caja;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Conexion;
import vista.Inventario0.nuevoMateriales;
import vista.proveedor.proveedornuevo;

/**
 *
 * @author ADSO
 */
public class EgresoProveedor extends javax.swing.JDialog {

    /**
     * Creates new form EgresoProveedor
     */
    private Egresos ingresoPanel;
    
   public EgresoProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarProveedores(); // Cargar proveedores en cmbStock1
        cargarProductos();  // Cargar productos en cmbStock2
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new rojeru_san.RSButtonRiple();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCancelar = new rojeru_san.RSButtonRiple();
        txtPago = new com.toedter.calendar.JDateChooser();
        txtCantidadnuevo = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel2 = new javax.swing.JLabel();
        txtDetallenuevo = new RSMaterialComponent.RSTextFieldMaterial();
        cmbStock = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbProveedor = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadnuevo1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel6 = new javax.swing.JLabel();
        cmbStock1 = new RSMaterialComponent.RSComboBoxMaterial();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 49, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century751 BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Egresos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        btnGuardar.setBackground(new java.awt.Color(46, 49, 82));
        btnGuardar.setText("Guardar");
        btnGuardar.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 16)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Descripcion:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Fecha Pago:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        btnCancelar.setBackground(new java.awt.Color(46, 49, 82));
        btnCancelar.setText("Volver");
        btnCancelar.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 16)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 180, -1));

        txtPago.setBackground(new java.awt.Color(255, 255, 255));
        txtPago.setForeground(new java.awt.Color(255, 255, 255));
        txtPago.setDateFormatString("y-MM-d");
        txtPago.setMaxSelectableDate(new java.util.Date(253370786472000L));
        jPanel1.add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 210, 30));

        txtCantidadnuevo.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidadnuevo.setPlaceholder("Ingrese cantidad de egreso");
        txtCantidadnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidadnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Monto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        txtDetallenuevo.setForeground(new java.awt.Color(0, 0, 0));
        txtDetallenuevo.setPlaceholder("Ingrese detalles de egreso");
        txtDetallenuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetallenuevoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDetallenuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 270, 30));

        cmbStock.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione categoria:", "Servicios Publicos", "Compra de Productos e Insumos", "Arriendo", "Nómina", "Prestamos", "Mantenimiento y reparaciones", "Transporte, domicilios y logistica ", "Otros" }));
        cmbStock.setColorMaterial(new java.awt.Color(0, 0, 0));
        cmbStock.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        cmbStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStockMouseClicked(evt);
            }
        });
        cmbStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStockActionPerformed(evt);
            }
        });
        jPanel1.add(cmbStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 270, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Categoria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 90, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 520, 2));

        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Proveedor:", "Item 1", "Item 2", "Item 3" }));
        cmbProveedor.setColorMaterial(new java.awt.Color(0, 0, 0));
        cmbProveedor.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        cmbProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbProveedorMouseClicked(evt);
            }
        });
        cmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(cmbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Proveedor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Cantidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, -1));

        txtCantidadnuevo1.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidadnuevo1.setPlaceholder("Ingrese cantidad");
        txtCantidadnuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadnuevo1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidadnuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 220, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Producto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 80, -1));

        cmbStock1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Producto:", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStock1.setColorMaterial(new java.awt.Color(0, 0, 0));
        cmbStock1.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        cmbStock1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStock1MouseClicked(evt);
            }
        });
        cmbStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStock1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbStock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 230, 30));

        jButton2.setBackground(new java.awt.Color(46, 49, 82));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus-pequeno.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 20, 20));

        jButton3.setBackground(new java.awt.Color(46, 49, 82));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus-pequeno.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
try {
            // Validar campos
            if (txtPago.getDate() == null) {
                mostrarError("Seleccione una fecha de pago");
                return;
            }
            if (txtDetallenuevo.getText().trim().isEmpty()) {
                mostrarError("Ingrese una descripción");
                return;
            }
            if (txtCantidadnuevo.getText().trim().isEmpty()) {
                mostrarError("Ingrese el monto del egreso");
                return;
            }
            if (cmbStock.getSelectedIndex() == 0) {
                mostrarError("Seleccione una categoría");
                return;
            }
            if (cmbProveedor.getSelectedIndex() == 0) {
                mostrarError("Seleccione un proveedor");
                return;
            }
            if (cmbStock1.getSelectedIndex() == 0) {
                mostrarError("Seleccione un producto");
                return;
            }
            if (txtCantidadnuevo1.getText().trim().isEmpty()) {
                mostrarError("Ingrese la cantidad del producto");
                return;
            }

            // Obtener valores
            java.sql.Date fecha = new java.sql.Date(txtPago.getDate().getTime());
            String descripcion = txtDetallenuevo.getText().trim();
            Double monto = Double.parseDouble(txtCantidadnuevo.getText().trim());
            String categoria = (String) cmbStock.getSelectedItem();
            String nombreProveedor = (String) cmbProveedor.getSelectedItem();
            String nombreProducto = (String) cmbStock1.getSelectedItem();
            int cantidad = Integer.parseInt(txtCantidadnuevo1.getText().trim());

            // Validar cantidad positiva
            if (cantidad <= 0) {
                mostrarError("La cantidad debe ser mayor que cero");
                return;
            }

            // IDs
            String idProveedor = obtenerIdProveedor(nombreProveedor);
            int idProducto = obtenerIdProducto(nombreProducto);
            if (idProveedor == null) {
                mostrarError("No se encontró el proveedor en la base de datos");
                return;
            }
            if (idProducto == -1) {
                mostrarError("No se encontró el producto en la base de datos");
                return;
            }

            // paso de datos
            try (Connection con = Conexion.getConnection()) {
                con.setAutoCommit(false); // Desactivar autocommit para transacción

                // Insertar egreso en tabla caja
                if (!insertarEtapa(fecha, descripcion, monto, categoria)) {
                    con.rollback();
                    return;
                }

                // Actualizar stock en inventario
                if (!actualizarStock(idProducto, cantidad)) {
                    con.rollback();
                    mostrarError("Error al actualizar el stock");
                    return;
                }

                // Insertar relación en suministra
                if (!insertarSuministra(idProveedor, idProducto)) {
                    con.rollback();
                    mostrarError("Error al registrar la relación proveedor-producto");
                    return;
                }

                // Confirmar transacción
                con.commit();
                mostrarMensaje("Registro guardado, stock actualizado y relación proveedor-producto registrada correctamente");
                this.dispose();

                if (ingresoPanel != null) {
                    // Aquí puedes actualizar la tabla de ingresoPanel si es necesario
                }
            } catch (SQLException e) {
                mostrarError("Error al guardar: " + e.getMessage());
                e.printStackTrace();
            }
        } catch (NumberFormatException e) {
            mostrarError("Monto o cantidad inválidos: " + e.getMessage());
        } catch (Exception e) {
            mostrarError("Error inesperado: " + e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCantidadnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadnuevoActionPerformed

    private void txtDetallenuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetallenuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetallenuevoActionPerformed

    private void cmbStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStockMouseClicked

    }//GEN-LAST:event_cmbStockMouseClicked

    private void cmbStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStockActionPerformed

    private void cmbProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProveedorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedorMouseClicked

    private void cmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedorActionPerformed

    private void txtCantidadnuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadnuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadnuevo1ActionPerformed

    private void cmbStock1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStock1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStock1MouseClicked

    private void cmbStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStock1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStock1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        proveedornuevo dialog = new proveedornuevo(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nuevoMateriales dialog = new nuevoMateriales(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
 
    private void cargarProveedores() {
        try (Connection con = Conexion.getConnection();
             PreparedStatement ps = con.prepareStatement("SELECT nombre FROM proveedor");
             ResultSet rs = ps.executeQuery()) {

            // Limpiar ComboBox
            cmbProveedor.removeAllItems();
            cmbProveedor.addItem("Seleccione un Proveedor:");

            // Agregar proveedores
            while (rs.next()) {
                cmbProveedor.addItem(rs.getString("nombre"));
            }
        } catch (SQLException e) {
            mostrarError("Error al cargar proveedores: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    
    private void cargarProductos() {
        try (Connection con = Conexion.getConnection();
             PreparedStatement ps = con.prepareStatement("SELECT nombre FROM inventario WHERE tipo = 'material'");
             ResultSet rs = ps.executeQuery()) {

            // Limpiar ComboBox
            cmbStock1.removeAllItems();
            cmbStock1.addItem("Seleccione Producto:");

            // Agregar productos
            while (rs.next()) {
                cmbStock1.addItem(rs.getString("nombre"));
            }
        } catch (SQLException e) {
            mostrarError("Error al cargar productos: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    
    private String obtenerIdProveedor(String nombreProveedor) {
        String sql = "SELECT id_proveedor FROM proveedor WHERE nombre = ?";
        try (Connection con = Conexion.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, nombreProveedor);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getString("id_proveedor");
                }
            }
        } catch (SQLException e) {
            mostrarError("Error al obtener ID del proveedor: " + e.getMessage());
            e.printStackTrace();
        }
        return null;
    }
    
    
    private int obtenerIdProducto(String nombreProducto) {
        String sql = "SELECT id_inventario FROM inventario WHERE nombre = ? AND tipo = 'material'";
        try (Connection con = Conexion.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, nombreProducto);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("id_inventario");
                }
            }
        } catch (SQLException e) {
            mostrarError("Error al obtener ID del producto: " + e.getMessage());
            e.printStackTrace();
        }
        return -1;
    }
    
    
    private boolean actualizarStock(int idProducto, int cantidad) {
        String sql = "UPDATE inventario SET cantidad = cantidad + ? WHERE id_inventario = ?";
        try (Connection con = Conexion.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, cantidad);
            ps.setInt(2, idProducto);
            int resultado = ps.executeUpdate();
            return resultado > 0;
        } catch (SQLException e) {
            mostrarError("Error al actualizar stock: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
    
    
    private boolean insertarSuministra(String idProveedor, int idProducto) {
        String sql = "INSERT INTO suministra (inventario_id_inventario, proveedor_id_proveedor) VALUES (?, ?)";
        try (Connection con = Conexion.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, idProducto);
            ps.setString(2, idProveedor); // id_proveedor es varchar
            int resultado = ps.executeUpdate();
            return resultado > 0;
        } catch (SQLException e) {
            mostrarError("Error al registrar suministra: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EgresoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EgresoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EgresoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EgresoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EgresoProveedor dialog = new EgresoProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnCancelar;
    private rojeru_san.RSButtonRiple btnGuardar;
    private RSMaterialComponent.RSComboBoxMaterial cmbProveedor;
    private RSMaterialComponent.RSComboBoxMaterial cmbStock;
    private RSMaterialComponent.RSComboBoxMaterial cmbStock1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private RSMaterialComponent.RSTextFieldMaterial txtCantidadnuevo;
    private RSMaterialComponent.RSTextFieldMaterial txtCantidadnuevo1;
    private RSMaterialComponent.RSTextFieldMaterial txtDetallenuevo;
    private com.toedter.calendar.JDateChooser txtPago;
    // End of variables declaration//GEN-END:variables
private boolean insertarEtapa(java.util.Date fecha, String descripcion, Double monto, String categoria) throws SQLException {
        String sql = "INSERT INTO caja (fecha, descripcion, monto, movimiento, categoria) VALUES (?, ?, ?, 'egreso', ?)";

        try (Connection con = Conexion.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            // Convertir java.util.Date a java.sql.Date
            ps.setDate(1, new java.sql.Date(fecha.getTime()));
            ps.setString(2, descripcion);
            ps.setDouble(3, monto);
            ps.setString(4, categoria);

            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                mostrarMensaje("Registro guardado correctamente");
                return true;
            }
        } catch (SQLException e) {
            mostrarError("Error de base de datos: " + e.getMessage());
            throw e; // Relanzar la excepción para manejo superior
        }
        return false;
    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

}
